INSERT INTO articulos (nombre, precio, stock) VALUES ('Teclado Mecánico RGB', 85.50, 15);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Ratón Inalámbrico Ergonómico', 42.25, 30);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Monitor 27 Pulgadas 4K', 299.99, 10);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Alfombrilla Gaming XL', 15.00, 50);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Auriculares con Cancelación de Ruido', 120.00, 8);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Cable HDMI 2.1 (2 metros)', 12.95, 100);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Soporte para Portátil Alumino', 35.40, 20);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Disco Duro Externo 2TB', 75.00, 25);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Memoria RAM 16GB DDR4', 65.20, 40);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Webcam 1080p Pro', 55.00, 12);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Altavoces Bluetooth 5.0', 45.90, 18);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Tarjeta de Memoria 128GB', 22.50, 60);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Silla de Oficina Ergonómica', 189.00, 5);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Lámpara de Escritorio LED', 29.99, 15);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Hub USB-C 7 en 1', 39.50, 22);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Micrófono de Condensador USB', 88.00, 7);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Pasta Térmica de Alto Rendimiento', 9.99, 45);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Ventilador para Caja 120mm', 14.50, 30);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Fuente de Alimentación 750W Gold', 110.00, 10);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Tarjeta Gráfica RTX 4060', 320.00, 4);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Pendrive 64GB USB 3.2', 11.20, 80);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Cargador Rápido 65W GaN', 34.00, 25);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Adaptador Bluetooth USB', 8.50, 50);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Mochila para Portátil 15.6"', 45.00, 14);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Protector de Pantalla Universal', 5.95, 200);
INSERT INTO articulos (nombre, precio, stock) VALUES ('SAI / UPS 800VA', 95.00, 6);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Impresora Multifunción Láser', 145.00, 9);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Cartucho de Tóner Negro', 48.20, 15);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Router Wi-Fi 6', 79.90, 11);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Extensor de Red PLC', 52.00, 13);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Disco SSD NVMe 1TB', 92.00, 28);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Funda para Tablet 10"', 18.00, 35);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Teclado Numérico Externo', 12.50, 20);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Limpiador de Pantallas Kit', 7.50, 40);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Base Refrigeradora Portátil', 26.90, 17);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Mando Gaming para PC', 38.00, 22);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Smartwatch Deportivo', 65.00, 19);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Soporte Monitor Brazo Articulado', 44.50, 12);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Cable Ethernet Cat 7 (10m)', 16.80, 45);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Organizador de Cables', 9.00, 60);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Lector de Tarjetas SD', 14.20, 25);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Batería Externa 20000mAh', 39.99, 18);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Mini PC Intel i5', 450.00, 3);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Cámara de Seguridad IP', 49.00, 14);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Pilas Recargables AA (pack 4)', 12.00, 55);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Caja para Disco Duro 2.5"', 15.50, 20);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Escáner de Documentos Portátil', 89.00, 5);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Tableta Digitalizadora', 75.40, 8);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Interruptor Inteligente Wi-Fi', 19.90, 30);
INSERT INTO articulos (nombre, precio, stock) VALUES ('Gafas de Luz Azul para Pantalla', 24.50, 25);